// Code generated by ent, DO NOT EDIT.

package secret

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dannegm/anubix-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldID, id))
}

// Ciphertext applies equality check predicate on the "ciphertext" field. It's identical to CiphertextEQ.
func Ciphertext(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCiphertext, v))
}

// Iv applies equality check predicate on the "iv" field. It's identical to IvEQ.
func Iv(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldIv, v))
}

// AuthTag applies equality check predicate on the "auth_tag" field. It's identical to AuthTagEQ.
func AuthTag(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldAuthTag, v))
}

// CiphertextEQ applies the EQ predicate on the "ciphertext" field.
func CiphertextEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldCiphertext, v))
}

// CiphertextNEQ applies the NEQ predicate on the "ciphertext" field.
func CiphertextNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldCiphertext, v))
}

// CiphertextIn applies the In predicate on the "ciphertext" field.
func CiphertextIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldCiphertext, vs...))
}

// CiphertextNotIn applies the NotIn predicate on the "ciphertext" field.
func CiphertextNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldCiphertext, vs...))
}

// CiphertextGT applies the GT predicate on the "ciphertext" field.
func CiphertextGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldCiphertext, v))
}

// CiphertextGTE applies the GTE predicate on the "ciphertext" field.
func CiphertextGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldCiphertext, v))
}

// CiphertextLT applies the LT predicate on the "ciphertext" field.
func CiphertextLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldCiphertext, v))
}

// CiphertextLTE applies the LTE predicate on the "ciphertext" field.
func CiphertextLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldCiphertext, v))
}

// CiphertextContains applies the Contains predicate on the "ciphertext" field.
func CiphertextContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldCiphertext, v))
}

// CiphertextHasPrefix applies the HasPrefix predicate on the "ciphertext" field.
func CiphertextHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldCiphertext, v))
}

// CiphertextHasSuffix applies the HasSuffix predicate on the "ciphertext" field.
func CiphertextHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldCiphertext, v))
}

// CiphertextEqualFold applies the EqualFold predicate on the "ciphertext" field.
func CiphertextEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldCiphertext, v))
}

// CiphertextContainsFold applies the ContainsFold predicate on the "ciphertext" field.
func CiphertextContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldCiphertext, v))
}

// IvEQ applies the EQ predicate on the "iv" field.
func IvEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldIv, v))
}

// IvNEQ applies the NEQ predicate on the "iv" field.
func IvNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldIv, v))
}

// IvIn applies the In predicate on the "iv" field.
func IvIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldIv, vs...))
}

// IvNotIn applies the NotIn predicate on the "iv" field.
func IvNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldIv, vs...))
}

// IvGT applies the GT predicate on the "iv" field.
func IvGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldIv, v))
}

// IvGTE applies the GTE predicate on the "iv" field.
func IvGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldIv, v))
}

// IvLT applies the LT predicate on the "iv" field.
func IvLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldIv, v))
}

// IvLTE applies the LTE predicate on the "iv" field.
func IvLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldIv, v))
}

// IvContains applies the Contains predicate on the "iv" field.
func IvContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldIv, v))
}

// IvHasPrefix applies the HasPrefix predicate on the "iv" field.
func IvHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldIv, v))
}

// IvHasSuffix applies the HasSuffix predicate on the "iv" field.
func IvHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldIv, v))
}

// IvEqualFold applies the EqualFold predicate on the "iv" field.
func IvEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldIv, v))
}

// IvContainsFold applies the ContainsFold predicate on the "iv" field.
func IvContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldIv, v))
}

// AuthTagEQ applies the EQ predicate on the "auth_tag" field.
func AuthTagEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEQ(FieldAuthTag, v))
}

// AuthTagNEQ applies the NEQ predicate on the "auth_tag" field.
func AuthTagNEQ(v string) predicate.Secret {
	return predicate.Secret(sql.FieldNEQ(FieldAuthTag, v))
}

// AuthTagIn applies the In predicate on the "auth_tag" field.
func AuthTagIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldIn(FieldAuthTag, vs...))
}

// AuthTagNotIn applies the NotIn predicate on the "auth_tag" field.
func AuthTagNotIn(vs ...string) predicate.Secret {
	return predicate.Secret(sql.FieldNotIn(FieldAuthTag, vs...))
}

// AuthTagGT applies the GT predicate on the "auth_tag" field.
func AuthTagGT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGT(FieldAuthTag, v))
}

// AuthTagGTE applies the GTE predicate on the "auth_tag" field.
func AuthTagGTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldGTE(FieldAuthTag, v))
}

// AuthTagLT applies the LT predicate on the "auth_tag" field.
func AuthTagLT(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLT(FieldAuthTag, v))
}

// AuthTagLTE applies the LTE predicate on the "auth_tag" field.
func AuthTagLTE(v string) predicate.Secret {
	return predicate.Secret(sql.FieldLTE(FieldAuthTag, v))
}

// AuthTagContains applies the Contains predicate on the "auth_tag" field.
func AuthTagContains(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContains(FieldAuthTag, v))
}

// AuthTagHasPrefix applies the HasPrefix predicate on the "auth_tag" field.
func AuthTagHasPrefix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasPrefix(FieldAuthTag, v))
}

// AuthTagHasSuffix applies the HasSuffix predicate on the "auth_tag" field.
func AuthTagHasSuffix(v string) predicate.Secret {
	return predicate.Secret(sql.FieldHasSuffix(FieldAuthTag, v))
}

// AuthTagEqualFold applies the EqualFold predicate on the "auth_tag" field.
func AuthTagEqualFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldEqualFold(FieldAuthTag, v))
}

// AuthTagContainsFold applies the ContainsFold predicate on the "auth_tag" field.
func AuthTagContainsFold(v string) predicate.Secret {
	return predicate.Secret(sql.FieldContainsFold(FieldAuthTag, v))
}

// HasBlock applies the HasEdge predicate on the "block" edge.
func HasBlock() predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlockTable, BlockColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlockWith applies the HasEdge predicate on the "block" edge with a given conditions (other predicates).
func HasBlockWith(preds ...predicate.Block) predicate.Secret {
	return predicate.Secret(func(s *sql.Selector) {
		step := newBlockStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Secret) predicate.Secret {
	return predicate.Secret(sql.NotPredicates(p))
}
