// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannegm/anubix-server/ent/attachment"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/predicate"
)

// AttachmentUpdate is the builder for updating Attachment entities.
type AttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *AttachmentMutation
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdate) Where(ps ...predicate.Attachment) *AttachmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *AttachmentUpdate) SetFilename(v string) *AttachmentUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableFilename(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AttachmentUpdate) SetMimeType(v string) *AttachmentUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableMimeType(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AttachmentUpdate) SetSizeBytes(v int) *AttachmentUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableSizeBytes(v *int) *AttachmentUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AttachmentUpdate) AddSizeBytes(v int) *AttachmentUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *AttachmentUpdate) SetCiphertext(v []byte) *AttachmentUpdate {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetIv sets the "iv" field.
func (_u *AttachmentUpdate) SetIv(v string) *AttachmentUpdate {
	_u.mutation.SetIv(v)
	return _u
}

// SetNillableIv sets the "iv" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableIv(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetIv(*v)
	}
	return _u
}

// SetAuthTag sets the "auth_tag" field.
func (_u *AttachmentUpdate) SetAuthTag(v string) *AttachmentUpdate {
	_u.mutation.SetAuthTag(v)
	return _u
}

// SetNillableAuthTag sets the "auth_tag" field if the given value is not nil.
func (_u *AttachmentUpdate) SetNillableAuthTag(v *string) *AttachmentUpdate {
	if v != nil {
		_u.SetAuthTag(*v)
	}
	return _u
}

// SetEntryID sets the "entry" edge to the Entry entity by ID.
func (_u *AttachmentUpdate) SetEntryID(id string) *AttachmentUpdate {
	_u.mutation.SetEntryID(id)
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *AttachmentUpdate) SetEntry(v *Entry) *AttachmentUpdate {
	return _u.SetEntryID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdate) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *AttachmentUpdate) ClearEntry() *AttachmentUpdate {
	_u.mutation.ClearEntry()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttachmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := attachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Attachment.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ciphertext(); ok {
		if err := attachment.CiphertextValidator(v); err != nil {
			return &ValidationError{Name: "ciphertext", err: fmt.Errorf(`ent: validator failed for field "Attachment.ciphertext": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Iv(); ok {
		if err := attachment.IvValidator(v); err != nil {
			return &ValidationError{Name: "iv", err: fmt.Errorf(`ent: validator failed for field "Attachment.iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthTag(); ok {
		if err := attachment.AuthTagValidator(v); err != nil {
			return &ValidationError{Name: "auth_tag", err: fmt.Errorf(`ent: validator failed for field "Attachment.auth_tag": %w`, err)}
		}
	}
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attachment.entry"`)
	}
	return nil
}

func (_u *AttachmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(attachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(attachment.FieldSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(attachment.FieldSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(attachment.FieldCiphertext, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Iv(); ok {
		_spec.SetField(attachment.FieldIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthTag(); ok {
		_spec.SetField(attachment.FieldAuthTag, field.TypeString, value)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.EntryTable,
			Columns: []string{attachment.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.EntryTable,
			Columns: []string{attachment.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttachmentUpdateOne is the builder for updating a single Attachment entity.
type AttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttachmentMutation
}

// SetFilename sets the "filename" field.
func (_u *AttachmentUpdateOne) SetFilename(v string) *AttachmentUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableFilename(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *AttachmentUpdateOne) SetMimeType(v string) *AttachmentUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableMimeType(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *AttachmentUpdateOne) SetSizeBytes(v int) *AttachmentUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableSizeBytes(v *int) *AttachmentUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *AttachmentUpdateOne) AddSizeBytes(v int) *AttachmentUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *AttachmentUpdateOne) SetCiphertext(v []byte) *AttachmentUpdateOne {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetIv sets the "iv" field.
func (_u *AttachmentUpdateOne) SetIv(v string) *AttachmentUpdateOne {
	_u.mutation.SetIv(v)
	return _u
}

// SetNillableIv sets the "iv" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableIv(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetIv(*v)
	}
	return _u
}

// SetAuthTag sets the "auth_tag" field.
func (_u *AttachmentUpdateOne) SetAuthTag(v string) *AttachmentUpdateOne {
	_u.mutation.SetAuthTag(v)
	return _u
}

// SetNillableAuthTag sets the "auth_tag" field if the given value is not nil.
func (_u *AttachmentUpdateOne) SetNillableAuthTag(v *string) *AttachmentUpdateOne {
	if v != nil {
		_u.SetAuthTag(*v)
	}
	return _u
}

// SetEntryID sets the "entry" edge to the Entry entity by ID.
func (_u *AttachmentUpdateOne) SetEntryID(id string) *AttachmentUpdateOne {
	_u.mutation.SetEntryID(id)
	return _u
}

// SetEntry sets the "entry" edge to the Entry entity.
func (_u *AttachmentUpdateOne) SetEntry(v *Entry) *AttachmentUpdateOne {
	return _u.SetEntryID(v.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (_u *AttachmentUpdateOne) Mutation() *AttachmentMutation {
	return _u.mutation
}

// ClearEntry clears the "entry" edge to the Entry entity.
func (_u *AttachmentUpdateOne) ClearEntry() *AttachmentUpdateOne {
	_u.mutation.ClearEntry()
	return _u
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (_u *AttachmentUpdateOne) Where(ps ...predicate.Attachment) *AttachmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttachmentUpdateOne) Select(field string, fields ...string) *AttachmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Attachment entity.
func (_u *AttachmentUpdateOne) Save(ctx context.Context) (*Attachment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttachmentUpdateOne) SaveX(ctx context.Context) *Attachment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttachmentUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := attachment.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Attachment.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Ciphertext(); ok {
		if err := attachment.CiphertextValidator(v); err != nil {
			return &ValidationError{Name: "ciphertext", err: fmt.Errorf(`ent: validator failed for field "Attachment.ciphertext": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Iv(); ok {
		if err := attachment.IvValidator(v); err != nil {
			return &ValidationError{Name: "iv", err: fmt.Errorf(`ent: validator failed for field "Attachment.iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthTag(); ok {
		if err := attachment.AuthTagValidator(v); err != nil {
			return &ValidationError{Name: "auth_tag", err: fmt.Errorf(`ent: validator failed for field "Attachment.auth_tag": %w`, err)}
		}
	}
	if _u.mutation.EntryCleared() && len(_u.mutation.EntryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Attachment.entry"`)
	}
	return nil
}

func (_u *AttachmentUpdateOne) sqlSave(ctx context.Context) (_node *Attachment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attachment.FieldID)
		for _, f := range fields {
			if !attachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(attachment.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(attachment.FieldSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(attachment.FieldSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(attachment.FieldCiphertext, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Iv(); ok {
		_spec.SetField(attachment.FieldIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthTag(); ok {
		_spec.SetField(attachment.FieldAuthTag, field.TypeString, value)
	}
	if _u.mutation.EntryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.EntryTable,
			Columns: []string{attachment.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.EntryTable,
			Columns: []string{attachment.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attachment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
