// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/entrytag"
	"github.com/dannegm/anubix-server/ent/tag"
)

// EntryTag is the model entity for the EntryTag schema.
type EntryTag struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntryTagQuery when eager-loading is set.
	Edges            EntryTagEdges `json:"edges"`
	entry_entry_tags *string
	tag_entry_tags   *string
	selectValues     sql.SelectValues
}

// EntryTagEdges holds the relations/edges for other nodes in the graph.
type EntryTagEdges struct {
	// Entry holds the value of the entry edge.
	Entry *Entry `json:"entry,omitempty"`
	// Tag holds the value of the tag edge.
	Tag *Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntryOrErr returns the Entry value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryTagEdges) EntryOrErr() (*Entry, error) {
	if e.Entry != nil {
		return e.Entry, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entry.Label}
	}
	return nil, &NotLoadedError{edge: "entry"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryTagEdges) TagOrErr() (*Tag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntryTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entrytag.FieldID:
			values[i] = new(sql.NullInt64)
		case entrytag.ForeignKeys[0]: // entry_entry_tags
			values[i] = new(sql.NullString)
		case entrytag.ForeignKeys[1]: // tag_entry_tags
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntryTag fields.
func (_m *EntryTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entrytag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case entrytag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_entry_tags", values[i])
			} else if value.Valid {
				_m.entry_entry_tags = new(string)
				*_m.entry_entry_tags = value.String
			}
		case entrytag.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag_entry_tags", values[i])
			} else if value.Valid {
				_m.tag_entry_tags = new(string)
				*_m.tag_entry_tags = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntryTag.
// This includes values selected through modifiers, order, etc.
func (_m *EntryTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntry queries the "entry" edge of the EntryTag entity.
func (_m *EntryTag) QueryEntry() *EntryQuery {
	return NewEntryTagClient(_m.config).QueryEntry(_m)
}

// QueryTag queries the "tag" edge of the EntryTag entity.
func (_m *EntryTag) QueryTag() *TagQuery {
	return NewEntryTagClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this EntryTag.
// Note that you need to call EntryTag.Unwrap() before calling this method if this EntryTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntryTag) Update() *EntryTagUpdateOne {
	return NewEntryTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntryTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntryTag) Unwrap() *EntryTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntryTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntryTag) String() string {
	var builder strings.Builder
	builder.WriteString("EntryTag(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// EntryTags is a parsable slice of EntryTag.
type EntryTags []*EntryTag
