// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannegm/anubix-server/ent/attachment"
	"github.com/dannegm/anubix-server/ent/auditlog"
	"github.com/dannegm/anubix-server/ent/block"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/entrytag"
	"github.com/dannegm/anubix-server/ent/sharetoken"
	"github.com/dannegm/anubix-server/ent/vault"
)

// EntryCreate is the builder for creating a Entry entity.
type EntryCreate struct {
	config
	mutation *EntryMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *EntryCreate) SetLabel(v string) *EntryCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *EntryCreate) SetIcon(v map[string]interface{}) *EntryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetPreview sets the "preview" field.
func (_c *EntryCreate) SetPreview(v string) *EntryCreate {
	_c.mutation.SetPreview(v)
	return _c
}

// SetNillablePreview sets the "preview" field if the given value is not nil.
func (_c *EntryCreate) SetNillablePreview(v *string) *EntryCreate {
	if v != nil {
		_c.SetPreview(*v)
	}
	return _c
}

// SetHasOtp sets the "has_otp" field.
func (_c *EntryCreate) SetHasOtp(v bool) *EntryCreate {
	_c.mutation.SetHasOtp(v)
	return _c
}

// SetNillableHasOtp sets the "has_otp" field if the given value is not nil.
func (_c *EntryCreate) SetNillableHasOtp(v *bool) *EntryCreate {
	if v != nil {
		_c.SetHasOtp(*v)
	}
	return _c
}

// SetIsFavorite sets the "is_favorite" field.
func (_c *EntryCreate) SetIsFavorite(v bool) *EntryCreate {
	_c.mutation.SetIsFavorite(v)
	return _c
}

// SetNillableIsFavorite sets the "is_favorite" field if the given value is not nil.
func (_c *EntryCreate) SetNillableIsFavorite(v *bool) *EntryCreate {
	if v != nil {
		_c.SetIsFavorite(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EntryCreate) SetCreatedAt(v time.Time) *EntryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EntryCreate) SetNillableCreatedAt(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EntryCreate) SetUpdatedAt(v time.Time) *EntryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EntryCreate) SetNillableUpdatedAt(v *time.Time) *EntryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EntryCreate) SetID(v string) *EntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EntryCreate) SetNillableID(v *string) *EntryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVaultID sets the "vault" edge to the Vault entity by ID.
func (_c *EntryCreate) SetVaultID(id string) *EntryCreate {
	_c.mutation.SetVaultID(id)
	return _c
}

// SetVault sets the "vault" edge to the Vault entity.
func (_c *EntryCreate) SetVault(v *Vault) *EntryCreate {
	return _c.SetVaultID(v.ID)
}

// AddBlockIDs adds the "blocks" edge to the Block entity by IDs.
func (_c *EntryCreate) AddBlockIDs(ids ...string) *EntryCreate {
	_c.mutation.AddBlockIDs(ids...)
	return _c
}

// AddBlocks adds the "blocks" edges to the Block entity.
func (_c *EntryCreate) AddBlocks(v ...*Block) *EntryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBlockIDs(ids...)
}

// AddAttachmentIDs adds the "attachments" edge to the Attachment entity by IDs.
func (_c *EntryCreate) AddAttachmentIDs(ids ...string) *EntryCreate {
	_c.mutation.AddAttachmentIDs(ids...)
	return _c
}

// AddAttachments adds the "attachments" edges to the Attachment entity.
func (_c *EntryCreate) AddAttachments(v ...*Attachment) *EntryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttachmentIDs(ids...)
}

// AddShareTokenIDs adds the "share_tokens" edge to the ShareToken entity by IDs.
func (_c *EntryCreate) AddShareTokenIDs(ids ...string) *EntryCreate {
	_c.mutation.AddShareTokenIDs(ids...)
	return _c
}

// AddShareTokens adds the "share_tokens" edges to the ShareToken entity.
func (_c *EntryCreate) AddShareTokens(v ...*ShareToken) *EntryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShareTokenIDs(ids...)
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_c *EntryCreate) AddAuditLogIDs(ids ...string) *EntryCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_c *EntryCreate) AddAuditLogs(v ...*AuditLog) *EntryCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// AddEntryTagIDs adds the "entry_tags" edge to the EntryTag entity by IDs.
func (_c *EntryCreate) AddEntryTagIDs(ids ...int) *EntryCreate {
	_c.mutation.AddEntryTagIDs(ids...)
	return _c
}

// AddEntryTags adds the "entry_tags" edges to the EntryTag entity.
func (_c *EntryCreate) AddEntryTags(v ...*EntryTag) *EntryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryTagIDs(ids...)
}

// Mutation returns the EntryMutation object of the builder.
func (_c *EntryCreate) Mutation() *EntryMutation {
	return _c.mutation
}

// Save creates the Entry in the database.
func (_c *EntryCreate) Save(ctx context.Context) (*Entry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EntryCreate) SaveX(ctx context.Context) *Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EntryCreate) defaults() {
	if _, ok := _c.mutation.HasOtp(); !ok {
		v := entry.DefaultHasOtp
		_c.mutation.SetHasOtp(v)
	}
	if _, ok := _c.mutation.IsFavorite(); !ok {
		v := entry.DefaultIsFavorite
		_c.mutation.SetIsFavorite(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := entry.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := entry.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := entry.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EntryCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "Entry.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := entry.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "Entry.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HasOtp(); !ok {
		return &ValidationError{Name: "has_otp", err: errors.New(`ent: missing required field "Entry.has_otp"`)}
	}
	if _, ok := _c.mutation.IsFavorite(); !ok {
		return &ValidationError{Name: "is_favorite", err: errors.New(`ent: missing required field "Entry.is_favorite"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Entry.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Entry.updated_at"`)}
	}
	if len(_c.mutation.VaultIDs()) == 0 {
		return &ValidationError{Name: "vault", err: errors.New(`ent: missing required edge "Entry.vault"`)}
	}
	return nil
}

func (_c *EntryCreate) sqlSave(ctx context.Context) (*Entry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Entry.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EntryCreate) createSpec() (*Entry, *sqlgraph.CreateSpec) {
	var (
		_node = &Entry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entry.Table, sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(entry.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(entry.FieldIcon, field.TypeJSON, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Preview(); ok {
		_spec.SetField(entry.FieldPreview, field.TypeString, value)
		_node.Preview = value
	}
	if value, ok := _c.mutation.HasOtp(); ok {
		_spec.SetField(entry.FieldHasOtp, field.TypeBool, value)
		_node.HasOtp = value
	}
	if value, ok := _c.mutation.IsFavorite(); ok {
		_spec.SetField(entry.FieldIsFavorite, field.TypeBool, value)
		_node.IsFavorite = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(entry.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(entry.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.VaultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   entry.VaultTable,
			Columns: []string{entry.VaultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.vault_entries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.BlocksTable,
			Columns: []string{entry.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(block.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttachmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AttachmentsTable,
			Columns: []string{entry.AttachmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShareTokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.ShareTokensTable,
			Columns: []string{entry.ShareTokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharetoken.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.AuditLogsTable,
			Columns: []string{entry.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntryTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   entry.EntryTagsTable,
			Columns: []string{entry.EntryTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entrytag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EntryCreateBulk is the builder for creating many Entry entities in bulk.
type EntryCreateBulk struct {
	config
	err      error
	builders []*EntryCreate
}

// Save creates the Entry entities in the database.
func (_c *EntryCreateBulk) Save(ctx context.Context) ([]*Entry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Entry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EntryCreateBulk) SaveX(ctx context.Context) []*Entry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
