// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/vault"
)

// Entry is the model entity for the Entry schema.
type Entry struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon map[string]interface{} `json:"icon,omitempty"`
	// Preview holds the value of the "preview" field.
	Preview string `json:"preview,omitempty"`
	// HasOtp holds the value of the "has_otp" field.
	HasOtp bool `json:"has_otp,omitempty"`
	// IsFavorite holds the value of the "is_favorite" field.
	IsFavorite bool `json:"is_favorite,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntryQuery when eager-loading is set.
	Edges         EntryEdges `json:"edges"`
	vault_entries *string
	selectValues  sql.SelectValues
}

// EntryEdges holds the relations/edges for other nodes in the graph.
type EntryEdges struct {
	// Vault holds the value of the vault edge.
	Vault *Vault `json:"vault,omitempty"`
	// Blocks holds the value of the blocks edge.
	Blocks []*Block `json:"blocks,omitempty"`
	// Attachments holds the value of the attachments edge.
	Attachments []*Attachment `json:"attachments,omitempty"`
	// ShareTokens holds the value of the share_tokens edge.
	ShareTokens []*ShareToken `json:"share_tokens,omitempty"`
	// AuditLogs holds the value of the audit_logs edge.
	AuditLogs []*AuditLog `json:"audit_logs,omitempty"`
	// EntryTags holds the value of the entry_tags edge.
	EntryTags []*EntryTag `json:"entry_tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// VaultOrErr returns the Vault value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntryEdges) VaultOrErr() (*Vault, error) {
	if e.Vault != nil {
		return e.Vault, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: vault.Label}
	}
	return nil, &NotLoadedError{edge: "vault"}
}

// BlocksOrErr returns the Blocks value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) BlocksOrErr() ([]*Block, error) {
	if e.loadedTypes[1] {
		return e.Blocks, nil
	}
	return nil, &NotLoadedError{edge: "blocks"}
}

// AttachmentsOrErr returns the Attachments value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) AttachmentsOrErr() ([]*Attachment, error) {
	if e.loadedTypes[2] {
		return e.Attachments, nil
	}
	return nil, &NotLoadedError{edge: "attachments"}
}

// ShareTokensOrErr returns the ShareTokens value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) ShareTokensOrErr() ([]*ShareToken, error) {
	if e.loadedTypes[3] {
		return e.ShareTokens, nil
	}
	return nil, &NotLoadedError{edge: "share_tokens"}
}

// AuditLogsOrErr returns the AuditLogs value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) AuditLogsOrErr() ([]*AuditLog, error) {
	if e.loadedTypes[4] {
		return e.AuditLogs, nil
	}
	return nil, &NotLoadedError{edge: "audit_logs"}
}

// EntryTagsOrErr returns the EntryTags value or an error if the edge
// was not loaded in eager-loading.
func (e EntryEdges) EntryTagsOrErr() ([]*EntryTag, error) {
	if e.loadedTypes[5] {
		return e.EntryTags, nil
	}
	return nil, &NotLoadedError{edge: "entry_tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Entry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entry.FieldIcon:
			values[i] = new([]byte)
		case entry.FieldHasOtp, entry.FieldIsFavorite:
			values[i] = new(sql.NullBool)
		case entry.FieldID, entry.FieldLabel, entry.FieldPreview:
			values[i] = new(sql.NullString)
		case entry.FieldCreatedAt, entry.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case entry.ForeignKeys[0]: // vault_entries
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Entry fields.
func (_m *Entry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case entry.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case entry.FieldIcon:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Icon); err != nil {
					return fmt.Errorf("unmarshal field icon: %w", err)
				}
			}
		case entry.FieldPreview:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preview", values[i])
			} else if value.Valid {
				_m.Preview = value.String
			}
		case entry.FieldHasOtp:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field has_otp", values[i])
			} else if value.Valid {
				_m.HasOtp = value.Bool
			}
		case entry.FieldIsFavorite:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_favorite", values[i])
			} else if value.Valid {
				_m.IsFavorite = value.Bool
			}
		case entry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entry.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vault_entries", values[i])
			} else if value.Valid {
				_m.vault_entries = new(string)
				*_m.vault_entries = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Entry.
// This includes values selected through modifiers, order, etc.
func (_m *Entry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVault queries the "vault" edge of the Entry entity.
func (_m *Entry) QueryVault() *VaultQuery {
	return NewEntryClient(_m.config).QueryVault(_m)
}

// QueryBlocks queries the "blocks" edge of the Entry entity.
func (_m *Entry) QueryBlocks() *BlockQuery {
	return NewEntryClient(_m.config).QueryBlocks(_m)
}

// QueryAttachments queries the "attachments" edge of the Entry entity.
func (_m *Entry) QueryAttachments() *AttachmentQuery {
	return NewEntryClient(_m.config).QueryAttachments(_m)
}

// QueryShareTokens queries the "share_tokens" edge of the Entry entity.
func (_m *Entry) QueryShareTokens() *ShareTokenQuery {
	return NewEntryClient(_m.config).QueryShareTokens(_m)
}

// QueryAuditLogs queries the "audit_logs" edge of the Entry entity.
func (_m *Entry) QueryAuditLogs() *AuditLogQuery {
	return NewEntryClient(_m.config).QueryAuditLogs(_m)
}

// QueryEntryTags queries the "entry_tags" edge of the Entry entity.
func (_m *Entry) QueryEntryTags() *EntryTagQuery {
	return NewEntryClient(_m.config).QueryEntryTags(_m)
}

// Update returns a builder for updating this Entry.
// Note that you need to call Entry.Unwrap() before calling this method if this Entry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Entry) Update() *EntryUpdateOne {
	return NewEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Entry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Entry) Unwrap() *Entry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Entry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Entry) String() string {
	var builder strings.Builder
	builder.WriteString("Entry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(fmt.Sprintf("%v", _m.Icon))
	builder.WriteString(", ")
	builder.WriteString("preview=")
	builder.WriteString(_m.Preview)
	builder.WriteString(", ")
	builder.WriteString("has_otp=")
	builder.WriteString(fmt.Sprintf("%v", _m.HasOtp))
	builder.WriteString(", ")
	builder.WriteString("is_favorite=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsFavorite))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Entries is a parsable slice of Entry.
type Entries []*Entry
