// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannegm/anubix-server/ent/block"
	"github.com/dannegm/anubix-server/ent/predicate"
	"github.com/dannegm/anubix-server/ent/secret"
)

// SecretUpdate is the builder for updating Secret entities.
type SecretUpdate struct {
	config
	hooks    []Hook
	mutation *SecretMutation
}

// Where appends a list predicates to the SecretUpdate builder.
func (_u *SecretUpdate) Where(ps ...predicate.Secret) *SecretUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *SecretUpdate) SetCiphertext(v string) *SecretUpdate {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetNillableCiphertext sets the "ciphertext" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableCiphertext(v *string) *SecretUpdate {
	if v != nil {
		_u.SetCiphertext(*v)
	}
	return _u
}

// SetIv sets the "iv" field.
func (_u *SecretUpdate) SetIv(v string) *SecretUpdate {
	_u.mutation.SetIv(v)
	return _u
}

// SetNillableIv sets the "iv" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableIv(v *string) *SecretUpdate {
	if v != nil {
		_u.SetIv(*v)
	}
	return _u
}

// SetAuthTag sets the "auth_tag" field.
func (_u *SecretUpdate) SetAuthTag(v string) *SecretUpdate {
	_u.mutation.SetAuthTag(v)
	return _u
}

// SetNillableAuthTag sets the "auth_tag" field if the given value is not nil.
func (_u *SecretUpdate) SetNillableAuthTag(v *string) *SecretUpdate {
	if v != nil {
		_u.SetAuthTag(*v)
	}
	return _u
}

// SetBlockID sets the "block" edge to the Block entity by ID.
func (_u *SecretUpdate) SetBlockID(id string) *SecretUpdate {
	_u.mutation.SetBlockID(id)
	return _u
}

// SetBlock sets the "block" edge to the Block entity.
func (_u *SecretUpdate) SetBlock(v *Block) *SecretUpdate {
	return _u.SetBlockID(v.ID)
}

// Mutation returns the SecretMutation object of the builder.
func (_u *SecretUpdate) Mutation() *SecretMutation {
	return _u.mutation
}

// ClearBlock clears the "block" edge to the Block entity.
func (_u *SecretUpdate) ClearBlock() *SecretUpdate {
	_u.mutation.ClearBlock()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecretUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecretUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecretUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecretUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecretUpdate) check() error {
	if v, ok := _u.mutation.Ciphertext(); ok {
		if err := secret.CiphertextValidator(v); err != nil {
			return &ValidationError{Name: "ciphertext", err: fmt.Errorf(`ent: validator failed for field "Secret.ciphertext": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Iv(); ok {
		if err := secret.IvValidator(v); err != nil {
			return &ValidationError{Name: "iv", err: fmt.Errorf(`ent: validator failed for field "Secret.iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthTag(); ok {
		if err := secret.AuthTagValidator(v); err != nil {
			return &ValidationError{Name: "auth_tag", err: fmt.Errorf(`ent: validator failed for field "Secret.auth_tag": %w`, err)}
		}
	}
	if _u.mutation.BlockCleared() && len(_u.mutation.BlockIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Secret.block"`)
	}
	return nil
}

func (_u *SecretUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(secret.Table, secret.Columns, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(secret.FieldCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.Iv(); ok {
		_spec.SetField(secret.FieldIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthTag(); ok {
		_spec.SetField(secret.FieldAuthTag, field.TypeString, value)
	}
	if _u.mutation.BlockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.BlockTable,
			Columns: []string{secret.BlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(block.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.BlockTable,
			Columns: []string{secret.BlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(block.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecretUpdateOne is the builder for updating a single Secret entity.
type SecretUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecretMutation
}

// SetCiphertext sets the "ciphertext" field.
func (_u *SecretUpdateOne) SetCiphertext(v string) *SecretUpdateOne {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetNillableCiphertext sets the "ciphertext" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableCiphertext(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetCiphertext(*v)
	}
	return _u
}

// SetIv sets the "iv" field.
func (_u *SecretUpdateOne) SetIv(v string) *SecretUpdateOne {
	_u.mutation.SetIv(v)
	return _u
}

// SetNillableIv sets the "iv" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableIv(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetIv(*v)
	}
	return _u
}

// SetAuthTag sets the "auth_tag" field.
func (_u *SecretUpdateOne) SetAuthTag(v string) *SecretUpdateOne {
	_u.mutation.SetAuthTag(v)
	return _u
}

// SetNillableAuthTag sets the "auth_tag" field if the given value is not nil.
func (_u *SecretUpdateOne) SetNillableAuthTag(v *string) *SecretUpdateOne {
	if v != nil {
		_u.SetAuthTag(*v)
	}
	return _u
}

// SetBlockID sets the "block" edge to the Block entity by ID.
func (_u *SecretUpdateOne) SetBlockID(id string) *SecretUpdateOne {
	_u.mutation.SetBlockID(id)
	return _u
}

// SetBlock sets the "block" edge to the Block entity.
func (_u *SecretUpdateOne) SetBlock(v *Block) *SecretUpdateOne {
	return _u.SetBlockID(v.ID)
}

// Mutation returns the SecretMutation object of the builder.
func (_u *SecretUpdateOne) Mutation() *SecretMutation {
	return _u.mutation
}

// ClearBlock clears the "block" edge to the Block entity.
func (_u *SecretUpdateOne) ClearBlock() *SecretUpdateOne {
	_u.mutation.ClearBlock()
	return _u
}

// Where appends a list predicates to the SecretUpdate builder.
func (_u *SecretUpdateOne) Where(ps ...predicate.Secret) *SecretUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecretUpdateOne) Select(field string, fields ...string) *SecretUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Secret entity.
func (_u *SecretUpdateOne) Save(ctx context.Context) (*Secret, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecretUpdateOne) SaveX(ctx context.Context) *Secret {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecretUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecretUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecretUpdateOne) check() error {
	if v, ok := _u.mutation.Ciphertext(); ok {
		if err := secret.CiphertextValidator(v); err != nil {
			return &ValidationError{Name: "ciphertext", err: fmt.Errorf(`ent: validator failed for field "Secret.ciphertext": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Iv(); ok {
		if err := secret.IvValidator(v); err != nil {
			return &ValidationError{Name: "iv", err: fmt.Errorf(`ent: validator failed for field "Secret.iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthTag(); ok {
		if err := secret.AuthTagValidator(v); err != nil {
			return &ValidationError{Name: "auth_tag", err: fmt.Errorf(`ent: validator failed for field "Secret.auth_tag": %w`, err)}
		}
	}
	if _u.mutation.BlockCleared() && len(_u.mutation.BlockIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Secret.block"`)
	}
	return nil
}

func (_u *SecretUpdateOne) sqlSave(ctx context.Context) (_node *Secret, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(secret.Table, secret.Columns, sqlgraph.NewFieldSpec(secret.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Secret.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, secret.FieldID)
		for _, f := range fields {
			if !secret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != secret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(secret.FieldCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.Iv(); ok {
		_spec.SetField(secret.FieldIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthTag(); ok {
		_spec.SetField(secret.FieldAuthTag, field.TypeString, value)
	}
	if _u.mutation.BlockCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.BlockTable,
			Columns: []string{secret.BlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(block.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BlockIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   secret.BlockTable,
			Columns: []string{secret.BlockColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(block.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Secret{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{secret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
