// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/predicate"
	"github.com/dannegm/anubix-server/ent/sharetoken"
	"github.com/dannegm/anubix-server/ent/user"
)

// ShareTokenQuery is the builder for querying ShareToken entities.
type ShareTokenQuery struct {
	config
	ctx           *QueryContext
	order         []sharetoken.OrderOption
	inters        []Interceptor
	predicates    []predicate.ShareToken
	withEntry     *EntryQuery
	withCreatedBy *UserQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShareTokenQuery builder.
func (_q *ShareTokenQuery) Where(ps ...predicate.ShareToken) *ShareTokenQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ShareTokenQuery) Limit(limit int) *ShareTokenQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ShareTokenQuery) Offset(offset int) *ShareTokenQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ShareTokenQuery) Unique(unique bool) *ShareTokenQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ShareTokenQuery) Order(o ...sharetoken.OrderOption) *ShareTokenQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryEntry chains the current query on the "entry" edge.
func (_q *ShareTokenQuery) QueryEntry() *EntryQuery {
	query := (&EntryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharetoken.Table, sharetoken.FieldID, selector),
			sqlgraph.To(entry.Table, entry.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharetoken.EntryTable, sharetoken.EntryColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreatedBy chains the current query on the "created_by" edge.
func (_q *ShareTokenQuery) QueryCreatedBy() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharetoken.Table, sharetoken.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharetoken.CreatedByTable, sharetoken.CreatedByColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ShareToken entity from the query.
// Returns a *NotFoundError when no ShareToken was found.
func (_q *ShareTokenQuery) First(ctx context.Context) (*ShareToken, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharetoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ShareTokenQuery) FirstX(ctx context.Context) *ShareToken {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ShareToken ID from the query.
// Returns a *NotFoundError when no ShareToken ID was found.
func (_q *ShareTokenQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharetoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ShareTokenQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ShareToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ShareToken entity is found.
// Returns a *NotFoundError when no ShareToken entities are found.
func (_q *ShareTokenQuery) Only(ctx context.Context) (*ShareToken, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharetoken.Label}
	default:
		return nil, &NotSingularError{sharetoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ShareTokenQuery) OnlyX(ctx context.Context) *ShareToken {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ShareToken ID in the query.
// Returns a *NotSingularError when more than one ShareToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ShareTokenQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharetoken.Label}
	default:
		err = &NotSingularError{sharetoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ShareTokenQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ShareTokens.
func (_q *ShareTokenQuery) All(ctx context.Context) ([]*ShareToken, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ShareToken, *ShareTokenQuery]()
	return withInterceptors[[]*ShareToken](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ShareTokenQuery) AllX(ctx context.Context) []*ShareToken {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ShareToken IDs.
func (_q *ShareTokenQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sharetoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ShareTokenQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ShareTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ShareTokenQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ShareTokenQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ShareTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ShareTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShareTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ShareTokenQuery) Clone() *ShareTokenQuery {
	if _q == nil {
		return nil
	}
	return &ShareTokenQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]sharetoken.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.ShareToken{}, _q.predicates...),
		withEntry:     _q.withEntry.Clone(),
		withCreatedBy: _q.withCreatedBy.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithEntry tells the query-builder to eager-load the nodes that are connected to
// the "entry" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShareTokenQuery) WithEntry(opts ...func(*EntryQuery)) *ShareTokenQuery {
	query := (&EntryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEntry = query
	return _q
}

// WithCreatedBy tells the query-builder to eager-load the nodes that are connected to
// the "created_by" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ShareTokenQuery) WithCreatedBy(opts ...func(*UserQuery)) *ShareTokenQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCreatedBy = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type sharetoken.Type `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ShareToken.Query().
//		GroupBy(sharetoken.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ShareTokenQuery) GroupBy(field string, fields ...string) *ShareTokenGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShareTokenGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sharetoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type sharetoken.Type `json:"type,omitempty"`
//	}
//
//	client.ShareToken.Query().
//		Select(sharetoken.FieldType).
//		Scan(ctx, &v)
func (_q *ShareTokenQuery) Select(fields ...string) *ShareTokenSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ShareTokenSelect{ShareTokenQuery: _q}
	sbuild.label = sharetoken.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShareTokenSelect configured with the given aggregations.
func (_q *ShareTokenQuery) Aggregate(fns ...AggregateFunc) *ShareTokenSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ShareTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sharetoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ShareTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ShareToken, error) {
	var (
		nodes       = []*ShareToken{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withEntry != nil,
			_q.withCreatedBy != nil,
		}
	)
	if _q.withEntry != nil || _q.withCreatedBy != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, sharetoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ShareToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ShareToken{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withEntry; query != nil {
		if err := _q.loadEntry(ctx, query, nodes, nil,
			func(n *ShareToken, e *Entry) { n.Edges.Entry = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCreatedBy; query != nil {
		if err := _q.loadCreatedBy(ctx, query, nodes, nil,
			func(n *ShareToken, e *User) { n.Edges.CreatedBy = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ShareTokenQuery) loadEntry(ctx context.Context, query *EntryQuery, nodes []*ShareToken, init func(*ShareToken), assign func(*ShareToken, *Entry)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ShareToken)
	for i := range nodes {
		if nodes[i].entry_share_tokens == nil {
			continue
		}
		fk := *nodes[i].entry_share_tokens
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(entry.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "entry_share_tokens" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ShareTokenQuery) loadCreatedBy(ctx context.Context, query *UserQuery, nodes []*ShareToken, init func(*ShareToken), assign func(*ShareToken, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*ShareToken)
	for i := range nodes {
		if nodes[i].user_share_tokens == nil {
			continue
		}
		fk := *nodes[i].user_share_tokens
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_share_tokens" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ShareTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ShareTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharetoken.Table, sharetoken.Columns, sqlgraph.NewFieldSpec(sharetoken.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharetoken.FieldID)
		for i := range fields {
			if fields[i] != sharetoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ShareTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sharetoken.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sharetoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ShareTokenGroupBy is the group-by builder for ShareToken entities.
type ShareTokenGroupBy struct {
	selector
	build *ShareTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ShareTokenGroupBy) Aggregate(fns ...AggregateFunc) *ShareTokenGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ShareTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShareTokenQuery, *ShareTokenGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ShareTokenGroupBy) sqlScan(ctx context.Context, root *ShareTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShareTokenSelect is the builder for selecting fields of ShareToken entities.
type ShareTokenSelect struct {
	*ShareTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ShareTokenSelect) Aggregate(fns ...AggregateFunc) *ShareTokenSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ShareTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShareTokenQuery, *ShareTokenSelect](ctx, _s.ShareTokenQuery, _s, _s.inters, v)
}

func (_s *ShareTokenSelect) sqlScan(ctx context.Context, root *ShareTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
