// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/sharetoken"
	"github.com/dannegm/anubix-server/ent/user"
)

// ShareToken is the model entity for the ShareToken schema.
type ShareToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type sharetoken.Type `json:"type,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey *string `json:"api_key,omitempty"`
	// APISecretHash holds the value of the "api_secret_hash" field.
	APISecretHash *string `json:"-"`
	// Ciphertext holds the value of the "ciphertext" field.
	Ciphertext *string `json:"ciphertext,omitempty"`
	// Iv holds the value of the "iv" field.
	Iv *string `json:"iv,omitempty"`
	// AuthTag holds the value of the "auth_tag" field.
	AuthTag *string `json:"auth_tag,omitempty"`
	// UseCount holds the value of the "use_count" field.
	UseCount int `json:"use_count,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShareTokenQuery when eager-loading is set.
	Edges              ShareTokenEdges `json:"edges"`
	entry_share_tokens *string
	user_share_tokens  *string
	selectValues       sql.SelectValues
}

// ShareTokenEdges holds the relations/edges for other nodes in the graph.
type ShareTokenEdges struct {
	// Entry holds the value of the entry edge.
	Entry *Entry `json:"entry,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *User `json:"created_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// EntryOrErr returns the Entry value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShareTokenEdges) EntryOrErr() (*Entry, error) {
	if e.Entry != nil {
		return e.Entry, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entry.Label}
	}
	return nil, &NotLoadedError{edge: "entry"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShareTokenEdges) CreatedByOrErr() (*User, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShareToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sharetoken.FieldUseCount:
			values[i] = new(sql.NullInt64)
		case sharetoken.FieldID, sharetoken.FieldType, sharetoken.FieldAPIKey, sharetoken.FieldAPISecretHash, sharetoken.FieldCiphertext, sharetoken.FieldIv, sharetoken.FieldAuthTag:
			values[i] = new(sql.NullString)
		case sharetoken.FieldUsedAt, sharetoken.FieldExpiresAt, sharetoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case sharetoken.ForeignKeys[0]: // entry_share_tokens
			values[i] = new(sql.NullString)
		case sharetoken.ForeignKeys[1]: // user_share_tokens
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShareToken fields.
func (_m *ShareToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sharetoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sharetoken.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = sharetoken.Type(value.String)
			}
		case sharetoken.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				_m.APIKey = new(string)
				*_m.APIKey = value.String
			}
		case sharetoken.FieldAPISecretHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_secret_hash", values[i])
			} else if value.Valid {
				_m.APISecretHash = new(string)
				*_m.APISecretHash = value.String
			}
		case sharetoken.FieldCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ciphertext", values[i])
			} else if value.Valid {
				_m.Ciphertext = new(string)
				*_m.Ciphertext = value.String
			}
		case sharetoken.FieldIv:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field iv", values[i])
			} else if value.Valid {
				_m.Iv = new(string)
				*_m.Iv = value.String
			}
		case sharetoken.FieldAuthTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_tag", values[i])
			} else if value.Valid {
				_m.AuthTag = new(string)
				*_m.AuthTag = value.String
			}
		case sharetoken.FieldUseCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field use_count", values[i])
			} else if value.Valid {
				_m.UseCount = int(value.Int64)
			}
		case sharetoken.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		case sharetoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case sharetoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sharetoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_share_tokens", values[i])
			} else if value.Valid {
				_m.entry_share_tokens = new(string)
				*_m.entry_share_tokens = value.String
			}
		case sharetoken.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_share_tokens", values[i])
			} else if value.Valid {
				_m.user_share_tokens = new(string)
				*_m.user_share_tokens = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShareToken.
// This includes values selected through modifiers, order, etc.
func (_m *ShareToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntry queries the "entry" edge of the ShareToken entity.
func (_m *ShareToken) QueryEntry() *EntryQuery {
	return NewShareTokenClient(_m.config).QueryEntry(_m)
}

// QueryCreatedBy queries the "created_by" edge of the ShareToken entity.
func (_m *ShareToken) QueryCreatedBy() *UserQuery {
	return NewShareTokenClient(_m.config).QueryCreatedBy(_m)
}

// Update returns a builder for updating this ShareToken.
// Note that you need to call ShareToken.Unwrap() before calling this method if this ShareToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShareToken) Update() *ShareTokenUpdateOne {
	return NewShareTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShareToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShareToken) Unwrap() *ShareToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShareToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShareToken) String() string {
	var builder strings.Builder
	builder.WriteString("ShareToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	if v := _m.APIKey; v != nil {
		builder.WriteString("api_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("api_secret_hash=<sensitive>")
	builder.WriteString(", ")
	if v := _m.Ciphertext; v != nil {
		builder.WriteString("ciphertext=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Iv; v != nil {
		builder.WriteString("iv=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AuthTag; v != nil {
		builder.WriteString("auth_tag=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("use_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UseCount))
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ShareTokens is a parsable slice of ShareToken.
type ShareTokens []*ShareToken
