// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannegm/anubix-server/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// AuthHash holds the value of the "auth_hash" field.
	AuthHash string `json:"-"`
	// Salt holds the value of the "salt" field.
	Salt string `json:"salt,omitempty"`
	// EmailVerifiedAt holds the value of the "email_verified_at" field.
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`
	// TwoFactorSecret holds the value of the "two_factor_secret" field.
	TwoFactorSecret *string `json:"-"`
	// TwoFactorEnabled holds the value of the "two_factor_enabled" field.
	TwoFactorEnabled bool `json:"two_factor_enabled,omitempty"`
	// PasswordResetToken holds the value of the "password_reset_token" field.
	PasswordResetToken *string `json:"password_reset_token,omitempty"`
	// PasswordResetExpiresAt holds the value of the "password_reset_expires_at" field.
	PasswordResetExpiresAt *time.Time `json:"password_reset_expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Vaults holds the value of the vaults edge.
	Vaults []*Vault `json:"vaults,omitempty"`
	// Devices holds the value of the devices edge.
	Devices []*Device `json:"devices,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// AuditLogs holds the value of the audit_logs edge.
	AuditLogs []*AuditLog `json:"audit_logs,omitempty"`
	// ShareTokens holds the value of the share_tokens edge.
	ShareTokens []*ShareToken `json:"share_tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// VaultsOrErr returns the Vaults value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) VaultsOrErr() ([]*Vault, error) {
	if e.loadedTypes[0] {
		return e.Vaults, nil
	}
	return nil, &NotLoadedError{edge: "vaults"}
}

// DevicesOrErr returns the Devices value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DevicesOrErr() ([]*Device, error) {
	if e.loadedTypes[1] {
		return e.Devices, nil
	}
	return nil, &NotLoadedError{edge: "devices"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[2] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[3] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// AuditLogsOrErr returns the AuditLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AuditLogsOrErr() ([]*AuditLog, error) {
	if e.loadedTypes[4] {
		return e.AuditLogs, nil
	}
	return nil, &NotLoadedError{edge: "audit_logs"}
}

// ShareTokensOrErr returns the ShareTokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ShareTokensOrErr() ([]*ShareToken, error) {
	if e.loadedTypes[5] {
		return e.ShareTokens, nil
	}
	return nil, &NotLoadedError{edge: "share_tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldTwoFactorEnabled:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldEmail, user.FieldAuthHash, user.FieldSalt, user.FieldTwoFactorSecret, user.FieldPasswordResetToken:
			values[i] = new(sql.NullString)
		case user.FieldEmailVerifiedAt, user.FieldPasswordResetExpiresAt, user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldAuthHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_hash", values[i])
			} else if value.Valid {
				_m.AuthHash = value.String
			}
		case user.FieldSalt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field salt", values[i])
			} else if value.Valid {
				_m.Salt = value.String
			}
		case user.FieldEmailVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field email_verified_at", values[i])
			} else if value.Valid {
				_m.EmailVerifiedAt = new(time.Time)
				*_m.EmailVerifiedAt = value.Time
			}
		case user.FieldTwoFactorSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field two_factor_secret", values[i])
			} else if value.Valid {
				_m.TwoFactorSecret = new(string)
				*_m.TwoFactorSecret = value.String
			}
		case user.FieldTwoFactorEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field two_factor_enabled", values[i])
			} else if value.Valid {
				_m.TwoFactorEnabled = value.Bool
			}
		case user.FieldPasswordResetToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_reset_token", values[i])
			} else if value.Valid {
				_m.PasswordResetToken = new(string)
				*_m.PasswordResetToken = value.String
			}
		case user.FieldPasswordResetExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field password_reset_expires_at", values[i])
			} else if value.Valid {
				_m.PasswordResetExpiresAt = new(time.Time)
				*_m.PasswordResetExpiresAt = value.Time
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVaults queries the "vaults" edge of the User entity.
func (_m *User) QueryVaults() *VaultQuery {
	return NewUserClient(_m.config).QueryVaults(_m)
}

// QueryDevices queries the "devices" edge of the User entity.
func (_m *User) QueryDevices() *DeviceQuery {
	return NewUserClient(_m.config).QueryDevices(_m)
}

// QuerySessions queries the "sessions" edge of the User entity.
func (_m *User) QuerySessions() *SessionQuery {
	return NewUserClient(_m.config).QuerySessions(_m)
}

// QueryTags queries the "tags" edge of the User entity.
func (_m *User) QueryTags() *TagQuery {
	return NewUserClient(_m.config).QueryTags(_m)
}

// QueryAuditLogs queries the "audit_logs" edge of the User entity.
func (_m *User) QueryAuditLogs() *AuditLogQuery {
	return NewUserClient(_m.config).QueryAuditLogs(_m)
}

// QueryShareTokens queries the "share_tokens" edge of the User entity.
func (_m *User) QueryShareTokens() *ShareTokenQuery {
	return NewUserClient(_m.config).QueryShareTokens(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("auth_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("salt=")
	builder.WriteString(_m.Salt)
	builder.WriteString(", ")
	if v := _m.EmailVerifiedAt; v != nil {
		builder.WriteString("email_verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("two_factor_secret=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("two_factor_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TwoFactorEnabled))
	builder.WriteString(", ")
	if v := _m.PasswordResetToken; v != nil {
		builder.WriteString("password_reset_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PasswordResetExpiresAt; v != nil {
		builder.WriteString("password_reset_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
