// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dannegm/anubix-server/ent/user"
	"github.com/dannegm/anubix-server/ent/vault"
)

// Vault is the model entity for the Vault schema.
type Vault struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// EncryptedVaultKey holds the value of the "encrypted_vault_key" field.
	EncryptedVaultKey string `json:"encrypted_vault_key,omitempty"`
	// VaultKeyIv holds the value of the "vault_key_iv" field.
	VaultKeyIv string `json:"vault_key_iv,omitempty"`
	// VaultKeyAuthTag holds the value of the "vault_key_auth_tag" field.
	VaultKeyAuthTag string `json:"vault_key_auth_tag,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VaultQuery when eager-loading is set.
	Edges        VaultEdges `json:"edges"`
	user_vaults  *string
	selectValues sql.SelectValues
}

// VaultEdges holds the relations/edges for other nodes in the graph.
type VaultEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Entries holds the value of the entries edge.
	Entries []*Entry `json:"entries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VaultEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// EntriesOrErr returns the Entries value or an error if the edge
// was not loaded in eager-loading.
func (e VaultEdges) EntriesOrErr() ([]*Entry, error) {
	if e.loadedTypes[1] {
		return e.Entries, nil
	}
	return nil, &NotLoadedError{edge: "entries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vault) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vault.FieldID, vault.FieldName, vault.FieldEncryptedVaultKey, vault.FieldVaultKeyIv, vault.FieldVaultKeyAuthTag:
			values[i] = new(sql.NullString)
		case vault.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case vault.ForeignKeys[0]: // user_vaults
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vault fields.
func (_m *Vault) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vault.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case vault.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case vault.FieldEncryptedVaultKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_vault_key", values[i])
			} else if value.Valid {
				_m.EncryptedVaultKey = value.String
			}
		case vault.FieldVaultKeyIv:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vault_key_iv", values[i])
			} else if value.Valid {
				_m.VaultKeyIv = value.String
			}
		case vault.FieldVaultKeyAuthTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vault_key_auth_tag", values[i])
			} else if value.Valid {
				_m.VaultKeyAuthTag = value.String
			}
		case vault.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vault.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_vaults", values[i])
			} else if value.Valid {
				_m.user_vaults = new(string)
				*_m.user_vaults = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vault.
// This includes values selected through modifiers, order, etc.
func (_m *Vault) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Vault entity.
func (_m *Vault) QueryUser() *UserQuery {
	return NewVaultClient(_m.config).QueryUser(_m)
}

// QueryEntries queries the "entries" edge of the Vault entity.
func (_m *Vault) QueryEntries() *EntryQuery {
	return NewVaultClient(_m.config).QueryEntries(_m)
}

// Update returns a builder for updating this Vault.
// Note that you need to call Vault.Unwrap() before calling this method if this Vault
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vault) Update() *VaultUpdateOne {
	return NewVaultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vault entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vault) Unwrap() *Vault {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vault is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vault) String() string {
	var builder strings.Builder
	builder.WriteString("Vault(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("encrypted_vault_key=")
	builder.WriteString(_m.EncryptedVaultKey)
	builder.WriteString(", ")
	builder.WriteString("vault_key_iv=")
	builder.WriteString(_m.VaultKeyIv)
	builder.WriteString(", ")
	builder.WriteString("vault_key_auth_tag=")
	builder.WriteString(_m.VaultKeyAuthTag)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Vaults is a parsable slice of Vault.
type Vaults []*Vault
