// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dannegm/anubix-server/ent/entry"
	"github.com/dannegm/anubix-server/ent/predicate"
	"github.com/dannegm/anubix-server/ent/user"
	"github.com/dannegm/anubix-server/ent/vault"
)

// VaultUpdate is the builder for updating Vault entities.
type VaultUpdate struct {
	config
	hooks    []Hook
	mutation *VaultMutation
}

// Where appends a list predicates to the VaultUpdate builder.
func (_u *VaultUpdate) Where(ps ...predicate.Vault) *VaultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *VaultUpdate) SetName(v string) *VaultUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableName(v *string) *VaultUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEncryptedVaultKey sets the "encrypted_vault_key" field.
func (_u *VaultUpdate) SetEncryptedVaultKey(v string) *VaultUpdate {
	_u.mutation.SetEncryptedVaultKey(v)
	return _u
}

// SetNillableEncryptedVaultKey sets the "encrypted_vault_key" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableEncryptedVaultKey(v *string) *VaultUpdate {
	if v != nil {
		_u.SetEncryptedVaultKey(*v)
	}
	return _u
}

// SetVaultKeyIv sets the "vault_key_iv" field.
func (_u *VaultUpdate) SetVaultKeyIv(v string) *VaultUpdate {
	_u.mutation.SetVaultKeyIv(v)
	return _u
}

// SetNillableVaultKeyIv sets the "vault_key_iv" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableVaultKeyIv(v *string) *VaultUpdate {
	if v != nil {
		_u.SetVaultKeyIv(*v)
	}
	return _u
}

// SetVaultKeyAuthTag sets the "vault_key_auth_tag" field.
func (_u *VaultUpdate) SetVaultKeyAuthTag(v string) *VaultUpdate {
	_u.mutation.SetVaultKeyAuthTag(v)
	return _u
}

// SetNillableVaultKeyAuthTag sets the "vault_key_auth_tag" field if the given value is not nil.
func (_u *VaultUpdate) SetNillableVaultKeyAuthTag(v *string) *VaultUpdate {
	if v != nil {
		_u.SetVaultKeyAuthTag(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *VaultUpdate) SetUserID(id string) *VaultUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VaultUpdate) SetUser(v *User) *VaultUpdate {
	return _u.SetUserID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *VaultUpdate) AddEntryIDs(ids ...string) *VaultUpdate {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *VaultUpdate) AddEntries(v ...*Entry) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the VaultMutation object of the builder.
func (_u *VaultUpdate) Mutation() *VaultMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VaultUpdate) ClearUser() *VaultUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *VaultUpdate) ClearEntries() *VaultUpdate {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *VaultUpdate) RemoveEntryIDs(ids ...string) *VaultUpdate {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *VaultUpdate) RemoveEntries(v ...*Entry) *VaultUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VaultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VaultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := vault.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vault.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedVaultKey(); ok {
		if err := vault.EncryptedVaultKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_vault_key", err: fmt.Errorf(`ent: validator failed for field "Vault.encrypted_vault_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultKeyIv(); ok {
		if err := vault.VaultKeyIvValidator(v); err != nil {
			return &ValidationError{Name: "vault_key_iv", err: fmt.Errorf(`ent: validator failed for field "Vault.vault_key_iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultKeyAuthTag(); ok {
		if err := vault.VaultKeyAuthTagValidator(v); err != nil {
			return &ValidationError{Name: "vault_key_auth_tag", err: fmt.Errorf(`ent: validator failed for field "Vault.vault_key_auth_tag": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vault.user"`)
	}
	return nil
}

func (_u *VaultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vault.Table, vault.Columns, sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vault.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedVaultKey(); ok {
		_spec.SetField(vault.FieldEncryptedVaultKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VaultKeyIv(); ok {
		_spec.SetField(vault.FieldVaultKeyIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.VaultKeyAuthTag(); ok {
		_spec.SetField(vault.FieldVaultKeyAuthTag, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.UserTable,
			Columns: []string{vault.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.UserTable,
			Columns: []string{vault.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vault.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VaultUpdateOne is the builder for updating a single Vault entity.
type VaultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VaultMutation
}

// SetName sets the "name" field.
func (_u *VaultUpdateOne) SetName(v string) *VaultUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableName(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEncryptedVaultKey sets the "encrypted_vault_key" field.
func (_u *VaultUpdateOne) SetEncryptedVaultKey(v string) *VaultUpdateOne {
	_u.mutation.SetEncryptedVaultKey(v)
	return _u
}

// SetNillableEncryptedVaultKey sets the "encrypted_vault_key" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableEncryptedVaultKey(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetEncryptedVaultKey(*v)
	}
	return _u
}

// SetVaultKeyIv sets the "vault_key_iv" field.
func (_u *VaultUpdateOne) SetVaultKeyIv(v string) *VaultUpdateOne {
	_u.mutation.SetVaultKeyIv(v)
	return _u
}

// SetNillableVaultKeyIv sets the "vault_key_iv" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableVaultKeyIv(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetVaultKeyIv(*v)
	}
	return _u
}

// SetVaultKeyAuthTag sets the "vault_key_auth_tag" field.
func (_u *VaultUpdateOne) SetVaultKeyAuthTag(v string) *VaultUpdateOne {
	_u.mutation.SetVaultKeyAuthTag(v)
	return _u
}

// SetNillableVaultKeyAuthTag sets the "vault_key_auth_tag" field if the given value is not nil.
func (_u *VaultUpdateOne) SetNillableVaultKeyAuthTag(v *string) *VaultUpdateOne {
	if v != nil {
		_u.SetVaultKeyAuthTag(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *VaultUpdateOne) SetUserID(id string) *VaultUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VaultUpdateOne) SetUser(v *User) *VaultUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the Entry entity by IDs.
func (_u *VaultUpdateOne) AddEntryIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.AddEntryIDs(ids...)
	return _u
}

// AddEntries adds the "entries" edges to the Entry entity.
func (_u *VaultUpdateOne) AddEntries(v ...*Entry) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEntryIDs(ids...)
}

// Mutation returns the VaultMutation object of the builder.
func (_u *VaultUpdateOne) Mutation() *VaultMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VaultUpdateOne) ClearUser() *VaultUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearEntries clears all "entries" edges to the Entry entity.
func (_u *VaultUpdateOne) ClearEntries() *VaultUpdateOne {
	_u.mutation.ClearEntries()
	return _u
}

// RemoveEntryIDs removes the "entries" edge to Entry entities by IDs.
func (_u *VaultUpdateOne) RemoveEntryIDs(ids ...string) *VaultUpdateOne {
	_u.mutation.RemoveEntryIDs(ids...)
	return _u
}

// RemoveEntries removes "entries" edges to Entry entities.
func (_u *VaultUpdateOne) RemoveEntries(v ...*Entry) *VaultUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEntryIDs(ids...)
}

// Where appends a list predicates to the VaultUpdate builder.
func (_u *VaultUpdateOne) Where(ps ...predicate.Vault) *VaultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VaultUpdateOne) Select(field string, fields ...string) *VaultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Vault entity.
func (_u *VaultUpdateOne) Save(ctx context.Context) (*Vault, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VaultUpdateOne) SaveX(ctx context.Context) *Vault {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VaultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VaultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VaultUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := vault.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vault.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedVaultKey(); ok {
		if err := vault.EncryptedVaultKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_vault_key", err: fmt.Errorf(`ent: validator failed for field "Vault.encrypted_vault_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultKeyIv(); ok {
		if err := vault.VaultKeyIvValidator(v); err != nil {
			return &ValidationError{Name: "vault_key_iv", err: fmt.Errorf(`ent: validator failed for field "Vault.vault_key_iv": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VaultKeyAuthTag(); ok {
		if err := vault.VaultKeyAuthTagValidator(v); err != nil {
			return &ValidationError{Name: "vault_key_auth_tag", err: fmt.Errorf(`ent: validator failed for field "Vault.vault_key_auth_tag": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Vault.user"`)
	}
	return nil
}

func (_u *VaultUpdateOne) sqlSave(ctx context.Context) (_node *Vault, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(vault.Table, vault.Columns, sqlgraph.NewFieldSpec(vault.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Vault.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, vault.FieldID)
		for _, f := range fields {
			if !vault.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != vault.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(vault.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedVaultKey(); ok {
		_spec.SetField(vault.FieldEncryptedVaultKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.VaultKeyIv(); ok {
		_spec.SetField(vault.FieldVaultKeyIv, field.TypeString, value)
	}
	if value, ok := _u.mutation.VaultKeyAuthTag(); ok {
		_spec.SetField(vault.FieldVaultKeyAuthTag, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.UserTable,
			Columns: []string{vault.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   vault.UserTable,
			Columns: []string{vault.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEntriesIDs(); len(nodes) > 0 && !_u.mutation.EntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vault.EntriesTable,
			Columns: []string{vault.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entry.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Vault{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{vault.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
