// Code generated by ent, DO NOT EDIT.

package sharetoken

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sharetoken type in the database.
	Label = "share_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldAPIKey holds the string denoting the api_key field in the database.
	FieldAPIKey = "api_key"
	// FieldAPISecretHash holds the string denoting the api_secret_hash field in the database.
	FieldAPISecretHash = "api_secret_hash"
	// FieldCiphertext holds the string denoting the ciphertext field in the database.
	FieldCiphertext = "ciphertext"
	// FieldIv holds the string denoting the iv field in the database.
	FieldIv = "iv"
	// FieldAuthTag holds the string denoting the auth_tag field in the database.
	FieldAuthTag = "auth_tag"
	// FieldUseCount holds the string denoting the use_count field in the database.
	FieldUseCount = "use_count"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEntry holds the string denoting the entry edge name in mutations.
	EdgeEntry = "entry"
	// EdgeCreatedBy holds the string denoting the created_by edge name in mutations.
	EdgeCreatedBy = "created_by"
	// Table holds the table name of the sharetoken in the database.
	Table = "share_tokens"
	// EntryTable is the table that holds the entry relation/edge.
	EntryTable = "share_tokens"
	// EntryInverseTable is the table name for the Entry entity.
	// It exists in this package in order to avoid circular dependency with the "entry" package.
	EntryInverseTable = "entries"
	// EntryColumn is the table column denoting the entry relation/edge.
	EntryColumn = "entry_share_tokens"
	// CreatedByTable is the table that holds the created_by relation/edge.
	CreatedByTable = "share_tokens"
	// CreatedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatedByInverseTable = "users"
	// CreatedByColumn is the table column denoting the created_by relation/edge.
	CreatedByColumn = "user_share_tokens"
)

// Columns holds all SQL columns for sharetoken fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldAPIKey,
	FieldAPISecretHash,
	FieldCiphertext,
	FieldIv,
	FieldAuthTag,
	FieldUseCount,
	FieldUsedAt,
	FieldExpiresAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "share_tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"entry_share_tokens",
	"user_share_tokens",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUseCount holds the default value on creation for the "use_count" field.
	DefaultUseCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypePermanent Type = "permanent"
	TypeExpiring  Type = "expiring"
	TypeOneTime   Type = "one_time"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypePermanent, TypeExpiring, TypeOneTime:
		return nil
	default:
		return fmt.Errorf("sharetoken: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the ShareToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByAPIKey orders the results by the api_key field.
func ByAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKey, opts...).ToFunc()
}

// ByAPISecretHash orders the results by the api_secret_hash field.
func ByAPISecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPISecretHash, opts...).ToFunc()
}

// ByCiphertext orders the results by the ciphertext field.
func ByCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCiphertext, opts...).ToFunc()
}

// ByIv orders the results by the iv field.
func ByIv(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIv, opts...).ToFunc()
}

// ByAuthTag orders the results by the auth_tag field.
func ByAuthTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthTag, opts...).ToFunc()
}

// ByUseCount orders the results by the use_count field.
func ByUseCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseCount, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEntryField orders the results by entry field.
func ByEntryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntryStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatedByField orders the results by created_by field.
func ByCreatedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatedByStep(), sql.OrderByField(field, opts...))
	}
}
func newEntryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntryTable, EntryColumn),
	)
}
func newCreatedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatedByTable, CreatedByColumn),
	)
}
