// Code generated by ent, DO NOT EDIT.

package entry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dannegm/anubix-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldID, id))
}

// Preview applies equality check predicate on the "preview" field. It's identical to PreviewEQ.
func Preview(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPreview, v))
}

// HasOtp applies equality check predicate on the "has_otp" field. It's identical to HasOtpEQ.
func HasOtp(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHasOtp, v))
}

// IsFavorite applies equality check predicate on the "is_favorite" field. It's identical to IsFavoriteEQ.
func IsFavorite(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldIsFavorite, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUpdatedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldLabel, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldIcon))
}

// PreviewEQ applies the EQ predicate on the "preview" field.
func PreviewEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldPreview, v))
}

// PreviewNEQ applies the NEQ predicate on the "preview" field.
func PreviewNEQ(v string) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldPreview, v))
}

// PreviewIn applies the In predicate on the "preview" field.
func PreviewIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldPreview, vs...))
}

// PreviewNotIn applies the NotIn predicate on the "preview" field.
func PreviewNotIn(vs ...string) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldPreview, vs...))
}

// PreviewGT applies the GT predicate on the "preview" field.
func PreviewGT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldPreview, v))
}

// PreviewGTE applies the GTE predicate on the "preview" field.
func PreviewGTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldPreview, v))
}

// PreviewLT applies the LT predicate on the "preview" field.
func PreviewLT(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldPreview, v))
}

// PreviewLTE applies the LTE predicate on the "preview" field.
func PreviewLTE(v string) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldPreview, v))
}

// PreviewContains applies the Contains predicate on the "preview" field.
func PreviewContains(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContains(FieldPreview, v))
}

// PreviewHasPrefix applies the HasPrefix predicate on the "preview" field.
func PreviewHasPrefix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasPrefix(FieldPreview, v))
}

// PreviewHasSuffix applies the HasSuffix predicate on the "preview" field.
func PreviewHasSuffix(v string) predicate.Entry {
	return predicate.Entry(sql.FieldHasSuffix(FieldPreview, v))
}

// PreviewIsNil applies the IsNil predicate on the "preview" field.
func PreviewIsNil() predicate.Entry {
	return predicate.Entry(sql.FieldIsNull(FieldPreview))
}

// PreviewNotNil applies the NotNil predicate on the "preview" field.
func PreviewNotNil() predicate.Entry {
	return predicate.Entry(sql.FieldNotNull(FieldPreview))
}

// PreviewEqualFold applies the EqualFold predicate on the "preview" field.
func PreviewEqualFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldEqualFold(FieldPreview, v))
}

// PreviewContainsFold applies the ContainsFold predicate on the "preview" field.
func PreviewContainsFold(v string) predicate.Entry {
	return predicate.Entry(sql.FieldContainsFold(FieldPreview, v))
}

// HasOtpEQ applies the EQ predicate on the "has_otp" field.
func HasOtpEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldHasOtp, v))
}

// HasOtpNEQ applies the NEQ predicate on the "has_otp" field.
func HasOtpNEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldHasOtp, v))
}

// IsFavoriteEQ applies the EQ predicate on the "is_favorite" field.
func IsFavoriteEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldIsFavorite, v))
}

// IsFavoriteNEQ applies the NEQ predicate on the "is_favorite" field.
func IsFavoriteNEQ(v bool) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldIsFavorite, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Entry {
	return predicate.Entry(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasVault applies the HasEdge predicate on the "vault" edge.
func HasVault() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VaultTable, VaultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVaultWith applies the HasEdge predicate on the "vault" edge with a given conditions (other predicates).
func HasVaultWith(preds ...predicate.Vault) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newVaultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlocks applies the HasEdge predicate on the "blocks" edge.
func HasBlocks() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BlocksTable, BlocksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlocksWith applies the HasEdge predicate on the "blocks" edge with a given conditions (other predicates).
func HasBlocksWith(preds ...predicate.Block) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newBlocksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttachments applies the HasEdge predicate on the "attachments" edge.
func HasAttachments() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttachmentsTable, AttachmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttachmentsWith applies the HasEdge predicate on the "attachments" edge with a given conditions (other predicates).
func HasAttachmentsWith(preds ...predicate.Attachment) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newAttachmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShareTokens applies the HasEdge predicate on the "share_tokens" edge.
func HasShareTokens() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ShareTokensTable, ShareTokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShareTokensWith applies the HasEdge predicate on the "share_tokens" edge with a given conditions (other predicates).
func HasShareTokensWith(preds ...predicate.ShareToken) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newShareTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuditLogs applies the HasEdge predicate on the "audit_logs" edge.
func HasAuditLogs() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuditLogsTable, AuditLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuditLogsWith applies the HasEdge predicate on the "audit_logs" edge with a given conditions (other predicates).
func HasAuditLogsWith(preds ...predicate.AuditLog) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newAuditLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntryTags applies the HasEdge predicate on the "entry_tags" edge.
func HasEntryTags() predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntryTagsTable, EntryTagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntryTagsWith applies the HasEdge predicate on the "entry_tags" edge with a given conditions (other predicates).
func HasEntryTagsWith(preds ...predicate.EntryTag) predicate.Entry {
	return predicate.Entry(func(s *sql.Selector) {
		step := newEntryTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Entry) predicate.Entry {
	return predicate.Entry(sql.NotPredicates(p))
}
