// Code generated by ent, DO NOT EDIT.

package vault

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the vault type in the database.
	Label = "vault"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEncryptedVaultKey holds the string denoting the encrypted_vault_key field in the database.
	FieldEncryptedVaultKey = "encrypted_vault_key"
	// FieldVaultKeyIv holds the string denoting the vault_key_iv field in the database.
	FieldVaultKeyIv = "vault_key_iv"
	// FieldVaultKeyAuthTag holds the string denoting the vault_key_auth_tag field in the database.
	FieldVaultKeyAuthTag = "vault_key_auth_tag"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeEntries holds the string denoting the entries edge name in mutations.
	EdgeEntries = "entries"
	// Table holds the table name of the vault in the database.
	Table = "vaults"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "vaults"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_vaults"
	// EntriesTable is the table that holds the entries relation/edge.
	EntriesTable = "entries"
	// EntriesInverseTable is the table name for the Entry entity.
	// It exists in this package in order to avoid circular dependency with the "entry" package.
	EntriesInverseTable = "entries"
	// EntriesColumn is the table column denoting the entries relation/edge.
	EntriesColumn = "vault_entries"
)

// Columns holds all SQL columns for vault fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEncryptedVaultKey,
	FieldVaultKeyIv,
	FieldVaultKeyAuthTag,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "vaults"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_vaults",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EncryptedVaultKeyValidator is a validator for the "encrypted_vault_key" field. It is called by the builders before save.
	EncryptedVaultKeyValidator func(string) error
	// VaultKeyIvValidator is a validator for the "vault_key_iv" field. It is called by the builders before save.
	VaultKeyIvValidator func(string) error
	// VaultKeyAuthTagValidator is a validator for the "vault_key_auth_tag" field. It is called by the builders before save.
	VaultKeyAuthTagValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Vault queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEncryptedVaultKey orders the results by the encrypted_vault_key field.
func ByEncryptedVaultKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedVaultKey, opts...).ToFunc()
}

// ByVaultKeyIv orders the results by the vault_key_iv field.
func ByVaultKeyIv(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVaultKeyIv, opts...).ToFunc()
}

// ByVaultKeyAuthTag orders the results by the vault_key_auth_tag field.
func ByVaultKeyAuthTag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVaultKeyAuthTag, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByEntriesCount orders the results by entries count.
func ByEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntriesStep(), opts...)
	}
}

// ByEntries orders the results by entries terms.
func ByEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
	)
}
