// Code generated by ent, DO NOT EDIT.

package vault

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/dannegm/anubix-server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Vault {
	return predicate.Vault(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Vault {
	return predicate.Vault(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldName, v))
}

// EncryptedVaultKey applies equality check predicate on the "encrypted_vault_key" field. It's identical to EncryptedVaultKeyEQ.
func EncryptedVaultKey(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldEncryptedVaultKey, v))
}

// VaultKeyIv applies equality check predicate on the "vault_key_iv" field. It's identical to VaultKeyIvEQ.
func VaultKeyIv(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldVaultKeyIv, v))
}

// VaultKeyAuthTag applies equality check predicate on the "vault_key_auth_tag" field. It's identical to VaultKeyAuthTagEQ.
func VaultKeyAuthTag(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldVaultKeyAuthTag, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContainsFold(FieldName, v))
}

// EncryptedVaultKeyEQ applies the EQ predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyNEQ applies the NEQ predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyNEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyIn applies the In predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldEncryptedVaultKey, vs...))
}

// EncryptedVaultKeyNotIn applies the NotIn predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyNotIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldEncryptedVaultKey, vs...))
}

// EncryptedVaultKeyGT applies the GT predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyGT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyGTE applies the GTE predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyGTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyLT applies the LT predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyLT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyLTE applies the LTE predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyLTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyContains applies the Contains predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyContains(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContains(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyHasPrefix applies the HasPrefix predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyHasPrefix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasPrefix(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyHasSuffix applies the HasSuffix predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyHasSuffix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasSuffix(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyEqualFold applies the EqualFold predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyEqualFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEqualFold(FieldEncryptedVaultKey, v))
}

// EncryptedVaultKeyContainsFold applies the ContainsFold predicate on the "encrypted_vault_key" field.
func EncryptedVaultKeyContainsFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContainsFold(FieldEncryptedVaultKey, v))
}

// VaultKeyIvEQ applies the EQ predicate on the "vault_key_iv" field.
func VaultKeyIvEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldVaultKeyIv, v))
}

// VaultKeyIvNEQ applies the NEQ predicate on the "vault_key_iv" field.
func VaultKeyIvNEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldVaultKeyIv, v))
}

// VaultKeyIvIn applies the In predicate on the "vault_key_iv" field.
func VaultKeyIvIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldVaultKeyIv, vs...))
}

// VaultKeyIvNotIn applies the NotIn predicate on the "vault_key_iv" field.
func VaultKeyIvNotIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldVaultKeyIv, vs...))
}

// VaultKeyIvGT applies the GT predicate on the "vault_key_iv" field.
func VaultKeyIvGT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldVaultKeyIv, v))
}

// VaultKeyIvGTE applies the GTE predicate on the "vault_key_iv" field.
func VaultKeyIvGTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldVaultKeyIv, v))
}

// VaultKeyIvLT applies the LT predicate on the "vault_key_iv" field.
func VaultKeyIvLT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldVaultKeyIv, v))
}

// VaultKeyIvLTE applies the LTE predicate on the "vault_key_iv" field.
func VaultKeyIvLTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldVaultKeyIv, v))
}

// VaultKeyIvContains applies the Contains predicate on the "vault_key_iv" field.
func VaultKeyIvContains(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContains(FieldVaultKeyIv, v))
}

// VaultKeyIvHasPrefix applies the HasPrefix predicate on the "vault_key_iv" field.
func VaultKeyIvHasPrefix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasPrefix(FieldVaultKeyIv, v))
}

// VaultKeyIvHasSuffix applies the HasSuffix predicate on the "vault_key_iv" field.
func VaultKeyIvHasSuffix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasSuffix(FieldVaultKeyIv, v))
}

// VaultKeyIvEqualFold applies the EqualFold predicate on the "vault_key_iv" field.
func VaultKeyIvEqualFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEqualFold(FieldVaultKeyIv, v))
}

// VaultKeyIvContainsFold applies the ContainsFold predicate on the "vault_key_iv" field.
func VaultKeyIvContainsFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContainsFold(FieldVaultKeyIv, v))
}

// VaultKeyAuthTagEQ applies the EQ predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagNEQ applies the NEQ predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagNEQ(v string) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagIn applies the In predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldVaultKeyAuthTag, vs...))
}

// VaultKeyAuthTagNotIn applies the NotIn predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagNotIn(vs ...string) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldVaultKeyAuthTag, vs...))
}

// VaultKeyAuthTagGT applies the GT predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagGT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagGTE applies the GTE predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagGTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagLT applies the LT predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagLT(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagLTE applies the LTE predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagLTE(v string) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagContains applies the Contains predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagContains(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContains(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagHasPrefix applies the HasPrefix predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagHasPrefix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasPrefix(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagHasSuffix applies the HasSuffix predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagHasSuffix(v string) predicate.Vault {
	return predicate.Vault(sql.FieldHasSuffix(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagEqualFold applies the EqualFold predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagEqualFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldEqualFold(FieldVaultKeyAuthTag, v))
}

// VaultKeyAuthTagContainsFold applies the ContainsFold predicate on the "vault_key_auth_tag" field.
func VaultKeyAuthTagContainsFold(v string) predicate.Vault {
	return predicate.Vault(sql.FieldContainsFold(FieldVaultKeyAuthTag, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Vault {
	return predicate.Vault(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Vault {
	return predicate.Vault(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Vault {
	return predicate.Vault(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEntries applies the HasEdge predicate on the "entries" edge.
func HasEntries() predicate.Vault {
	return predicate.Vault(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntriesWith applies the HasEdge predicate on the "entries" edge with a given conditions (other predicates).
func HasEntriesWith(preds ...predicate.Entry) predicate.Vault {
	return predicate.Vault(func(s *sql.Selector) {
		step := newEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Vault) predicate.Vault {
	return predicate.Vault(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Vault) predicate.Vault {
	return predicate.Vault(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Vault) predicate.Vault {
	return predicate.Vault(sql.NotPredicates(p))
}
